### ISSUE TITLE
Navbar inconsistent on the blog posts

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#115]
On the blog posts, the navbar does not currently show any of the signed in linked (like login, or profile/logout when you're logged in). See the page [here](https://esfiddle.net/blog/es2016-es7-final-feature-set).

These links need adding to the navbar on blog posts. The order should be the same as the homepage:
- Profile (only shown when a user is logged in)
- About
- Blog
- Login/Logout (depending on whether the user is logged in)

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

**Comment by xianrusso** [comment]
Howdy!
I'd love to take this on. 

Upon an inspection with dev tools, it seems the nav contains the same content as it does on other pages, so it's very perplexing why the "Login/Logout" isn't showing up specifically for the blog post... seems like a fun challenge!

**Comment by joshghent** [comment]
@xianrusso Huh interesting, thanks for looking into that. Because those buttons are shown dynamically then it might be worth looking into what the authentication api is returning to those blog post pages, perhaps it wasn't added. If you need help @asiyani is probably your man as he did all the authentication stuff.

**Comment by rodolv1979** [comment]
Hallo @joshghent, 
if this is still open I would be happy to take a look at it. 
Thanks
Rodolfo

**Comment by asiyani** [comment]
Sorry @rodolv1979  this one is already fixed. Thank you for taking interest in esfiddle. There are other issues open have a look. let us know if you can help.
if any issue let us know. 
Thank you. 👍

**Comment by rodolv1979** [comment]
Ok @asiyani, thanks, even tough the project that I have cloned is still having this problem in the Blog page.  I will work on it for exercise.
This is a really great project! I would be really happy to participate (that would be my first PR), I will take a look to the current issues for beginners/first timers only. If you have something in mind I am here, do not hesitate to contact me. 
Cheers
Many thanks!

**Comment by asiyani** [comment]
I have just merged new PR regarding Blog and About page issue. please update your repo and still, an issue let me know.

**Comment by rodolv1979** [comment]
Sorry but I am having few problems with Mongo. 
Unfortunately the issue seems still there, here is a screenshot.  
Am I making something wrong? Which branch should I pick up? Master or Develop?
Thank you
![screenshot from 2017-06-12 20-27-01](https://user-images.githubusercontent.com/18237060/27048910-dfa80e4c-4fad-11e7-950f-052cb7d31baf.png)

**Comment by asiyani** [comment]
You should clone develop branch. 
![image](https://user-images.githubusercontent.com/7142320/27049081-1fdedc1e-4fa6-11e7-85b6-5c6cac9ea27b.png)

**Comment by rodolv1979** [comment]
Yes I did it from develop branch but probably I misunderstood initially the bug/issue. If you click on the first post of the Blog page, in the new page  the nav-bar will not display anymore About Blog Login but just About Blog (like my picture). I thought that was the problem to be fixed.

**Comment by asiyani** [comment]
@rodolv1979 I am sorry. you are right it doesn't work when we click on blog. Please look into this for us. I am reopening this issue. 
Thanks...

**Comment by rodolv1979** [comment]
@asiyani it will be a pleasure! How much time do I have? I will start tomorrow evening, doing it at my best. I hope it is enough. 
Thank you

**Comment by asiyani** [comment]
Hey
Take your time, there is no rush.
Thank you.
